<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FoundryAgents.Core\FoundryAgents.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\tickets.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
