# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/apiops-cli/main/schemas/v1/extractor-config.schema.json
apis:
  - foundry-openai-v1
backends:
  - foundry-backend
namedValues:
  - foundry-api-audience
  - foundry-rate-limit-calls
  - tier-bronze-tokens-per-minute
  - tier-bronze-token-quota
  - tier-silver-tokens-per-minute
  - tier-silver-token-quota
  - tier-gold-tokens-per-minute
  - tier-gold-token-quota
products:
  - foundry-demo
  - foundry-bronze
  - foundry-silver
  - foundry-gold
tags: []
versionSets: []
loggers: []
diagnostics: []
groups: []
policyFragments: []
gateways: []
schemas: []
subscriptions: []
policies: []
policyRestrictions: []
documentations: []
workspaces: []

